version: "3"
services:
  mysql:
    container_name: uopp-mysql
    image: 'mysql:8.0.31'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=uopp
    ports:
      - "4306:3306"
    volumes:
      - ./uopp-init.sql:/docker-entrypoint-initdb.d/uopp-init.sql
  maildev:
    container_name: uopp-maildev
    image: maildev/maildev
    restart: always
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "4080:1080"
      - "4025:1025"